<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Kavya" name="Mytest" tests="5" failures="4" timestamp="7 Aug 2018 10:08:48 GMT" time="0.154" errors="0">
  <testcase name="againlogin" time="0.044" classname="retrylogicTest.myretrylogicTest"/>
  <testcase name="login" time="0.01" classname="retrylogicTest.myretrylogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at retrylogicTest.myretrylogicTest.login(myretrylogicTest.java:11)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="login" time="0.011" classname="retrylogicTest.myretrylogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at retrylogicTest.myretrylogicTest.login(myretrylogicTest.java:11)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="login" time="0.003" classname="retrylogicTest.myretrylogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at retrylogicTest.myretrylogicTest.login(myretrylogicTest.java:11)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="login" time="0.003" classname="retrylogicTest.myretrylogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at retrylogicTest.myretrylogicTest.login(myretrylogicTest.java:11)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Mytest -->
